version: '3.8'

services:
  cinema-api:
    container_name: cinema-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Server=mysql;Database=cinema_db;User=root;Password=password;"

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: "cinema_db"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
